global using Darling.Extensions;
global using Darling.Helpers;
global using Darling.Interfaces;
global using Darling.Services;
global using Darling.Structs;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Serilog;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Drawing.Imaging;
global using System.Diagnostics;
global using System.Globalization;
global using System.Runtime.InteropServices;
global using Tesseract;
global using Emgu.CV;
global using Emgu.CV.CvEnum;
global using Emgu.CV.Structure;

global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
global using ImageFormat = System.Drawing.Imaging.ImageFormat;